export const ACTIONS = {
  FETCH_NOTES: "FETCH_NOTES",
  FETCHED_NOTES: "FETCHED_NOTES",
  ERROR_OCCURRED: "ERROR_OCCURRED",
  CREATE_NEW_NOTE: "CREATE_NEW_NOTE",
  DELETE_NOTE: "DELETE_NOTE",
  DELETED_NOTE: "DELETED_NOTE",
  CLOSE_DELETION_ALERT: "CLOSE_DELETION_ALERT",
  UPDATE_NOTE: "UPDATE_NOTE",
  UPDATED_NOTE: "UPDATED_NOTE",
};
