export const ACTIONS = {
  FETCH_DOCS: "FETCH_DOCS",
  FETCHED_DOCS: "FETCHED_DOCS",
  CREATE_NEW_DOC: "CREATE_NEW_DOC",
  DELETE_DOC: "DELETE_DOC",
  DELETED_DOC: "DELETED_DOC",
  CLOSE_DELETION_ALERT: "CLOSE_DELETION_ALERT",
};
